### ISSUE TITLE
How to add openai api key?

### ISSUE THREAD

**Issue by markredito** [fleet-ai/context#10]
This might be related to issue #9 

When I run `context` I am not prompted to put in an api key? Any suggestions how to put an api key? Perhaps a config file somewhere? I didn't find any.

Here's a screenshot:
![image](https://github.com/fleet-ai/context/assets/64991342/95f942d4-de87-4975-bc7c-016c96323ab7)

Thank you!

**Comment by adrwz** [comment]
Hey @markredito! Try running `export OPENAI_API_KEY=<your openai api key>` and running Fleet Context again. Let me know if that works for you.

**Comment by adrwz** [comment]
Hey @markredito! Seems like this is because you're on an old version of openai. You can run `pip install --upgrade openai` and it should be resolved.

Newer versions of the library require openai>=1.1.0.

**Comment by markredito** [comment]
Wonderful! Thanks for the help!
