### ISSUE TITLE
Local mode by default, no way to not use local

### ISSUE THREAD

**Issue by synoet** [fleet-ai/context#12]
Seems like by default local mode is turned on.
![CleanShot 2023-11-08 at 21 43 22](https://github.com/fleet-ai/context/assets/10552019/da2709db-c51a-4e63-aae2-84e98d9e3577)

Specifying a model also doesn't stop it. I assume the intended behavior is if a model is not specified to either attempt to pull the model or hit a hosted model.
![CleanShot 2023-11-08 at 21 43 48](https://github.com/fleet-ai/context/assets/10552019/6b860cea-e72c-46fa-8a03-0fe5d641d2f8)

the --local flag also doesn't take a value like "false", and since local is turned on by default i'm not sure how to escape it.

**Comment by zer0kg** [comment]
Facing the exact same issue here
```
fleet-context==1.0.16
openai==1.2.0
```

**Comment by adrwz** [comment]
@synoet @zer0kg just fixed! Run `pip install --upgrade fleet-context` to resolve.

**Comment by zer0kg** [comment]
Thank you @adrwz! Works now
