### ISSUE TITLE
Questions about the vector database

### ISSUE THREAD

**Issue by lukasl-dev** [fleet-ai/context#21]
Hi there 👋

I have a few questions about the context's vector database, which is only mentioned once in the `README.md`. 

- **What library versions are stored in the vector database?** Only the latest major/minor version?
- **How responsive is the vector database to library updates?** Especially for (breaking) major version releases?
- **Do you plan to extend the existing vector database with more libraries?** I believe it would be awesome to discover newer or smaller libraries using context.
- **Is it or will it be possible to self-host a vector database?**

Maybe I have overseen some already answered questions in the readme. If so, sorry for that 😅

**Comment by big-nico** [comment]
Hey! Appreciate your interest in the project :)

1. We store the latest major version. We are working on also storing historical context. This would enable users to ask questions like "what were the major changes between pydantic version 1.0 vs 2.0" and get meaningful answers. It would also enable you to filter and ask questions only about a specific version of a library like "what was deprecated in numpy 1.26.2"
2. The vector database is updated regularly. Right now every month for each library if we detect a change. In the future we want to make updates more or less frequent on a library-specific basis.
3. We would love to add more libraries. Join our [discord ](https://discord.com/invite/YTc98S77aZ) & send your suggestions!
4. We are very interested in adding self-hosted vector dbs. Feel free to make a PR! Right now we have a hosted pinecone instance with all the vectors - but you can download any of the vectors on our website or via the CLI!
