### ISSUE TITLE
JSONDecodeError: Address error thrown when empty input is provided

### ISSUE THREAD

**Issue by jamino30** [fleet-ai/context#5]
Currently, if a user clicks Enter with no input provided, the following error is thrown:

<img width="832" alt="Screenshot 2023-11-08 at 1 06 20 PM" src="https://github.com/fleet-ai/context/assets/79227536/cf62e6a9-e08e-46ff-b7c6-b21ed2cd46b9">

**Comment by alecswjo** [comment]
Fixed by #6!
